### ISSUE TITLE
Memory access error when custom_specs folder doesn't exist

### ISSUE THREAD

**Issue by fllaca** [Adhara-Tech/enval#49]
# Steps to reproduce﻿

1. create a `.enval.manifest.yaml` config using a non-existing path in the `custom_specs` field.
2. run `enval` using that manifest

# Expected behavior

Enval executes the checks using the default tool specs and shows a warning saying that the `custom_specs`folder doesn't exist.

# Actual behavior

Enval crashes with a moemory access error and showing a stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13abddf]

goroutine 1 [running]:
github.com/Adhara-Tech/enval/pkg/infra.FileSystemToolsStorage.findInFileSystem.func1(0xc00012f268, 0x7, 0x0, 0x0, 0x15d7640, 0xc0001e60f0, 0x0, 0x14e3ea0)
        /Users/fllaca/projects/enval/pkg/infra/filesystem_tools_storage.go:29 +0x2f
path/filepath.Walk(0xc00012f268, 0x7, 0xc0001755a8, 0x15cc680, 0xc0001755d8)
        /usr/local/go/src/path/filepath/path.go:404 +0x6a
github.com/Adhara-Tech/enval/pkg/infra.FileSystemToolsStorage.findInFileSystem(0xc00012f268, 0x7, 0xc00012f298, 0x4, 0xc00015aaa0, 0x197, 0xc00015aa01)
        /Users/fllaca/projects/enval/pkg/infra/filesystem_tools_storage.go:28 +0x90
github.com/Adhara-Tech/enval/pkg/infra.FileSystemToolsStorage.Find(0xc00012f268, 0x7, 0xc00012f298, 0x4, 0x6, 0x0, 0x0)
        /Users/fllaca/projects/enval/pkg/infra/filesystem_tools_storage.go:62 +0x4d
github.com/Adhara-Tech/enval/pkg/infra.ToolsStorageChain.Find(0xc000123420, 0x2, 0x2, 0xc00012f298, 0x4, 0x0, 0x1b4, 0x14)
        /Users/fllaca/projects/enval/pkg/infra/chainned_tools_storage.go:27 +0x79
github.com/Adhara-Tech/enval/pkg/adapters.DefaultToolsStorageAdapter.Find(...)
        /Users/fllaca/projects/enval/pkg/adapters/tools_storage_adapter.go:39
github.com/Adhara-Tech/enval/pkg/manifestchecker.ToolsManager.ValidateTool(0x15d7060, 0xc000113dd0, 0x15db500, 0x1935488, 0xc0001e60c0, 0xc00012f298, 0x4, 0x0, 0x0, 0x0, ...)
        /Users/fllaca/projects/enval/pkg/manifestchecker/tool_checker_manager.go:67 +0x66
github.com/Adhara-Tech/enval/pkg/manifestchecker.ToolsManager.ValidateManifestAndNotify(0x15d7060, 0xc000113dd0, 0x15db500, 0x1935488, 0xc0001e60c0, 0xc000130c20, 0x1c, 0xc00012f268, 0x7, 0xc000152300, ...)
        /Users/fllaca/projects/enval/pkg/manifestchecker/tool_checker_manager.go:44 +0x112
main.executeCmd(0x1902580, 0x1935488, 0x0, 0x0, 0x0, 0x0)
        /Users/fllaca/projects/enval/cmd/enval.go:93 +0x46e
github.com/spf13/cobra.(*Command).execute(0x1902580, 0xc0001121e0, 0x0, 0x0, 0x1902580, 0xc0001121e0)
        /Users/fllaca/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x1902580, 0xc000175f60, 0x1, 0x1)
        /Users/fllaca/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/fllaca/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /Users/fllaca/projects/enval/cmd/enval.go:49 +0x1ec

```

**Comment by hrodes** [comment]
Custom spec section is optional in manifest. I think that if the directory does not exist, the tool should stop and show and error without executing anything. The error message can propose to create the directory or remove the section in the manifest
